source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'mongoid', '2.0.0.rc.6'
gem 'bson_ext', '~> 1.2'
gem 'devise'
gem 'inherited_resources'
gem 'haml'
gem 'simple_form'
gem 'show_for'
gem 'rpm_contrib'
gem 'compass'
gem 'compass-960-plugin', require: 'ninesixty'
gem 'hassle', git: 'https://github.com/koppen/hassle.git'

group :development, :test do
  gem 'rspec-rails'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'spork', '0.9.0.rc3'
  gem 'launchy'
  gem 'factory_girl_rails'
  gem 'pickle'
  gem 'autotest-rails'
  gem 'database_cleaner'
end
